INFO : 2021-05-13 13:29:40,360 : ------------- Launching Pathfinder -------------
INFO : 2021-05-13 13:29:40,412 : Opening main window
INFO : 2021-05-13 13:29:45,076 : Pressed forward button
INFO : 2021-05-13 13:29:45,396 : Pressed left button
INFO : 2021-05-13 13:29:45,768 : Pressed back button
INFO : 2021-05-13 13:29:46,058 : Pressed right button
INFO : 2021-05-13 13:29:54,571 : Pressed brake button
ERROR : 2021-05-13 13:31:19,952 : Unhandled exception in listener callback
Traceback (most recent call last):
  File "C:\Users\Niklas\AppData\Local\Programs\Python\Python38\lib\site-packages\pynput\_util\__init__.py", line 211, in inner
    return f(self, *args, **kwargs)
  File "C:\Users\Niklas\AppData\Local\Programs\Python\Python38\lib\site-packages\pynput\keyboard\_win32.py", line 287, in _process
    self.on_release(key)
  File "C:\Users\Niklas\AppData\Local\Programs\Python\Python38\lib\site-packages\pynput\_util\__init__.py", line 127, in inner
    if f(*args) is False:
  File "C:/Users/Niklas/Desktop/group-08/GUI Pycharm/GUI_Pathfinder.py", line 453, in on_release
    self.keyPressed.emit(key)
TypeError: KeyMonitor.keyPressed[KeyCode].emit(): argument 1 has unexpected type 'Key'
INFO : 2021-05-13 13:31:50,646 : Pressed back button
INFO : 2021-05-13 13:31:54,472 : Pressed forward button
INFO : 2021-05-13 13:31:55,952 : Pressed right button
INFO : 2021-05-13 13:31:57,096 : Pressed forward button
